name: Build and Deploy Package
on:
  push:
    branches:
      - main
    paths:
      - 'InterfaceDefs/INT-*.mf'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ID2 }}
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_DEFAULT_OUTPUT: json
      
  ID: ${{ github.run_id }}-${{ github.run_attempt }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preReqs:
    #runs-on: [self-hosted, linux, X64]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2

  #  - name: AWS Cli
  #    id: install-aws-cli
  #    uses: unfor19/install-aws-cli-action@v1
  #    with:
  #      version: 2                         # default
  #      verbose: false                     # default
  #      arch: amd64                        # allowed values: amd64, arm64
        
      - name: Install AWS CLI v2 and OS Packages
        run:  |
          sudo apt-get install -y curl
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "${GITHUB_WORKSPACE}/awscliv2.zip"
          #unzip -q /tmp/awscliv2.zip -d /tmp
          #unzip -q ${GITHUB_WORKSPACE}/awscliv2.zip -d ${GITHUB_WORKSPACE}/awscli
          #rm ${GITHUB_WORKSPACE}/awscliv2.zip
          #sudo /tmp/aws/install --update
          #rm -rf /tmp/aws/

          mkdir -p ${GITHUB_WORKSPACE}/tmp
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            _BDCURL=$(grep '^BDCTestURL=' $file | cut -f2 -d'=')
            __BDCTestFile=$(grep '^BDCTestFile=' $file | cut -f2 -d'=')
            _BDCTestFile=$(echo $__BDCTestFile | sed "s/\"//g")
            _processId=$(jq -r ".processId" ${GITHUB_WORKSPACE}/$_BDCTestFile)
            
            _resultFile=$(echo $_BDCTestFile | awk -F/ '{print $NF}' | tr -d ' ' | sed "s/\"//g ; s/'//g")
            _BDCAuth=${{ secrets.BDC }}

            curl -so ${GITHUB_WORKSPACE}/tmp/$_resultFile.out -d @$_BDCTestFile --location $_BDCURL --header 'Content-Type: application/json' --header "Authorization: Basic $_BDCAuth"
            cat ${GITHUB_WORKSPACE}/tmp/$_resultFile.out

            _testSuiteExecutionId=$(jq -r '.testSuiteExecutionId' ${GITHUB_WORKSPACE}/tmp/$_resultFile.out)
            echo output: $_testSuiteExecutionId

            _BDCURLTestExecutionSuite=$(echo $_BDCURL | sed "s/executeTest$/getTestExecutions?processId=/g")
            _BDCURLTestExecutionSuite=$_BDCURLTestExecutionSuite$_processId"&testSuiteExecutionId="$_testSuiteExecutionId
            echo test execution URL: $_BDCURLTestExecutionSuite
            
            sleep 30
            curl -so ${GITHUB_WORKSPACE}/tmp/$_resultFile.exec.out --location $_BDCURLTestExecutionSuite --header 'Content-Type: application/json' --header "Authorization: Basic $_BDCAuth"
            cat ${GITHUB_WORKSPACE}/tmp/$_resultFile.exec.out
            #http://localhost:9090/ws/simple/getTestExecutions?processId=14970c43-775f-4921-ab22-720566c70dfa&testSuiteExecutionId=d7ae0d33-bd88-40d9-b1f5-6d9049e6f1e5
          done
  
          deployPackageHWM=5        
          echo "deploy=$deployPackageHWM" >> "$GITHUB_OUTPUT"
          

  
