name: Build and Deploy Package
on:
  push:
    branches:
      - main
    paths:
      - 'InterfaceDefs/INT-*.mf'
env:
  envDev: "1.Dev"
  envTest: "2.Dev"
  envProd: "3.Prod"
  ID: ${{ github.run_id }}-${{ github.run_attempt }}

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preReqs:
    runs-on: [self-hosted, linux, X64]
    steps:
    - name: AWS Cli
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2                         # default
        verbose: false                     # default
        arch: amd64                        # allowed values: amd64, arm64
        
    - name: Install AWS CLI v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ID2 }}
      run:  |
          sudo apt install jq
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

          _pass=$(aws secretsmanager get-secret-value --secret-id employees | jq -r ".SecretString" | awk -F ":" '{ print $2 }' | sed "s/^\"//g ; s/\"}//g")
          echo $_pass
