name: Build and Deploy Package
on:
  push:
    branches:
      - main
    paths:
      - 'InterfaceDefs/INT-*.mf'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ID2 }}
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_DEFAULT_OUTPUT: json
      
  ID: ${{ github.run_id }}-${{ github.run_attempt }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preReqs:
    #runs-on: [self-hosted, linux, X64]
    runs-on: [ubuntu-latest]
    steps:
  #  - name: AWS Cli
  #    id: install-aws-cli
  #    uses: unfor19/install-aws-cli-action@v1
  #    with:
  #      version: 2                         # default
  #      verbose: false                     # default
  #      arch: amd64                        # allowed values: amd64, arm64
        
    - name: Install AWS CLI v2 and OS Packages
      run:  |
          sudo apt-get install -y curl libxml2-utils jq
          ls -ltr /usr/bin/xmllint
          xmllint
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "${GITHUB_WORKSPACE}/awscliv2.zip"
          #unzip -q /tmp/awscliv2.zip -d /tmp
          #unzip -q ${GITHUB_WORKSPACE}/awscliv2.zip -d ${GITHUB_WORKSPACE}/awscli
          #rm ${GITHUB_WORKSPACE}/awscliv2.zip
          #sudo /tmp/aws/install --update
          #rm -rf /tmp/aws/
          
          deployPackageHWM=5        
          echo "deploy=$deployPackageHWM" >> "$GITHUB_OUTPUT"

  
