name: Build and Package
on:
  push:
    branches:
      - main
    paths:
      - 'InterfaceDefs/INT*.mf'

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  createPackage:
    runs-on: [self-hosted]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
        #  fetch-depth: 0
        #  path: INT-001

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2
        #with:
        #  path: INT-001
        
      # Runs a set of commands using the runners shell
      - name: Build Package
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
            compNotes=$(grep '^buildNotes=' $file | cut -f2 -d'=')
            codeXML=$(grep '^codeXML=' $file | cut -f2 -d'=')

            export WD="${GITHUB_WORKSPACE}/boomicicd-cli/cli/scripts"
            export WORKSPACE="${GITHUB_WORKSPACE}/boomicicd-cli/cli/scripts"
            
            chmod +x "${WD}/bin/common.sh"
            "${WD}/bin/common.sh"
            
            chmod +x "${WD}/initcrPackage.sh"
            chmod +x "${WD}/initcrPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" extractComponentXmlFolder="$codeXML"
          done
