name: Create Package
on:
  push:
    branches:
      - main
    paths:
      - 'InterfaceDefs/INT*Build.mf'

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CreatePackage:
    runs-on: [self-hosted, linux, X64]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
        #  fetch-depth: 0
        #  path: INT-001

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2


      # Runs a set of commands using the runners shell
      - name: Create Package
        run: |
          BoomiAccount=${{ vars.BOOMI_ACCOUNT }}
          BoomiUsername=${{ vars.BOOMI_USERNAME }}
          API=${{ secrets.API }}
          RepoURL=${{ github.server_url }}
          RepoName=${{ github.repository }}
          RepoPath=${RepoURL}/${RepoName}
          GITUsername=${{ github.repository_owner }}
          GITUseremail=${{ vars.EMAIL }}
          CodeFolderXML=${{ vars.CODEFOLDER }}
          POSTMAN=${{ secrets.POSTMAN }}
          
          postmanInst=0
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            funcTest=0
            
            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
            compType=$(grep '^componentType=' $file | cut -f2 -d'=')
            compVer=$(grep '^ver=' $file | cut -f2 -d'=')
            packageVersion=$(grep '^ver=' $file | cut -f2 -d'=')
            envName=$(grep '^targetEnv=' $file | cut -f2 -d'=')
            env=$(grep '^targetEnv=' $file | cut -f2 -d'=')
            listenerStatus=$(grep '^listenerStatus=' $file | cut -f2 -d'=')
            compNotes=$(grep '^buildNotes=' $file | cut -f2 -d'=')
            deployPackage=$(grep '^deploy=' $file | cut -f2 -d'=')
            collectionId=$(grep '^collectionId=' $file | cut -f2 -d'=')
            testId=$(grep '^testId=' $file | cut -f2 -d'=')
            funcTest=$(grep '^funcTest=' $file | cut -f2 -d'=')

            export WD=${GITHUB_WORKSPACE}/cli/scripts/
            export WORKSPACE=${GITHUB_WORKSPACE}/cli/scripts/
            export GITHUB_WORKSPACE

            if [ $postmanInst == 0  && $funcTest == 1 ]
            then
              #sudo apt-get install -y curl
              #sh 'curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh'
              /usr/local/bin/postman login --with-api-key $POSTMAN
              postmanInst=1
            fi
            
            find ${GITHUB_WORKSPACE} -name *.sh -exec chmod 700 {} \;
            find ${GITHUB_WORKSPACE} -name *.sh -exec ls -ltr {} \;

            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh"
            chmod +x ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh
            chmod +x "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh"

            source "${GITHUB_WORKSPACE}/cli/scripts/bin/propertiesCICD.sh" $BoomiAccount $BoomiUsername $API $RepoPath $GITUsername $GITUseremail $CodeFolderXML
            source ${GITHUB_WORKSPACE}/cli/scripts/bin/common.sh

            "${GITHUB_WORKSPACE}/cli/scripts/initcrPackage.sh" componentId=$compId packageVersion=$compVer componentType=$compType notes="$compNotes" extractComponentXmlFolder="$CodeFolderXML"

            if [ $deployPackage == 1 ]
            then
              "${GITHUB_WORKSPACE}/cli/scripts/initdeployPackage.sh" componentId=$compId packageVersion=$packageVersion componentType=$compType notes="$compNotes" env=$env listenerStatus=$listenerStatus
            fi

            if [ $funcTest == 1 ]
            then
              echo Running Postman Collection
              _postmanOut=$(/usr/local/bin/postman collection run "$collectionId" -i "$testId" | grep test-scripts | sed 's/  *//g')
              echo output: $_postmanOut
              _postmanResult=$(echo $_postmanOut | awk -F "|" '{ print $3 }')
              if [ $_postmanResult != "1" ]
              then
                  echo "::error Postman test failed"
                  exit 1
              elif [ $_postmanResult == "0" ]
              then
                echo "Postman test OK"
                exit 0
              fi
            fi
          done
