# This is a basic workflow to help you get started with Actions

name: Deploy Environment Extensions
on:
  push:
    branches:
      - main
    paths:
      - 'InterfaceDefs/EnvironmentExt.mf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createPackage:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, X64]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
        #  fetch-depth: 0
        #  path: INT-001

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2
        #with:
        #  path: INT-001
        
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run:  cat ${{ github.workspace }}/README.md

      # Runs a set of commands using the runners shell
      - name: Update Environment Extensions
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            compId=$(grep '^componentId=' $file | cut -f2 -d'=')
            
            export WD=~/src/boomicicd-cli/cli/scripts
            export WORKSPACE=~/src/boomicicd-cli/cli/scripts
            
            chmod +x ~/src/boomicicd-cli/cli/scripts/bin/common.sh
            ~/src/boomicicd-cli/cli/scripts/bin/common.sh
            
            chmod +x ~/src/boomicicd-cli/cli/scripts/initcrPackage.sh
            ~/src/boomicicd-cli/cli/scripts/bin/updateExtensions.sh $file
          done
